### ISSUE TITLE
Adding the ASN description history (which is/was in BGP Ranking)

### ISSUE THREAD

**Issue by adulau** [D4-project/IPASN-History#1]
Adding the ASN description history (which is/was in BGP Ranking)

**Comment by Rafiot** [comment]
It is in bgpranking. The way to get that information will be to go through BGP Ranking, not IPASN History.

I'm working on the API for BGP Ranking right now.

**Comment by adulau** [comment]
Indeed, the idea is to expose it via the IPASN History API and the background is pulled from BGP Ranking API. Then it's a single query via IPASN History. A small question, should we separate IPASN History server and client in two separated repository to make it simpler to install?

**Comment by Rafiot** [comment]
IPASN History should be kept as simple as possible as it can handle a very high amount of requests and adding more options will make it slower.
Currently, the public instance of IPASN History is accessible through BGP Ranking, and you can query it with `pyipasnhistory` (will be on pypi soon):

``` bash
pip install git+https://github.com/D4-project/IPASN-History.git/#egg=pyipasnhistory&subdirectory=client
```

`pybgpranking` will have methods that allow to query everything.

**Comment by Rafiot** [comment]
Also solved.
