### ISSUE TITLE
minor thing: hg clone bgpdump does not work anymore

### ISSUE THREAD

**Issue by aaronkaplan** [D4-project/IPASN-History#12]
hg clone https://bitbucket.org/ripencc/bgpdump

--> returns 404.
I suggest you want to use this here?

https://github.com/RIPE-NCC/bgpdump

**Comment by Rafiot** [comment]
Is it needed? Is doing that not not enough: https://github.com/D4-project/IPASN-History#optional-build--install-bgpdumpy-required-to-process-dumps-from-ripe
If not this script can/should go.

I don't think I have it installed.

**Comment by adulau** [comment]
bgpdumpy is used in https://github.com/D4-project/IPASN-History/blob/8948f11f5860eea8011b0a4dda3b75eede8439f3/bin/ripe_loader.py - Thanks for the PR @aaronkaplan 

We don't use anymore the ripe_loader.py? @Rafiot
