### ISSUE TITLE
mypy cache issue in the github actions

### ISSUE THREAD

**Issue by aaronkaplan** [D4-project/IPASN-History#19]
Hi, when merging in #18 you will see that the github actions break in mypy.

I did a bit of research and it seems that this error is discussed also here https://github.com/python/mypy/issues/2960.
One trick could be to pass the parameter `--cache-dir=/dev/null` to mypy.

You might want to consider this.

**Comment by Rafiot** [comment]
It's failing because a few ignored lines don't need to be ignored anymore. I'll fix that later.

**Comment by aaronkaplan** [comment]
okay, got it.
Then please ignore my PR. Just noticed that also then creates further problems. I'll close it.

**Comment by Rafiot** [comment]
all good, fixed.
